A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [2]:
import numpy as np

# Create a nested list
data = [
    [10, 20, 25, 30, 40],
    [45, 50, 60, 65, 70],
    [75, 80, 90, 95, 100]
]

# Convert the nested list into a NumPy array
A = np.array(data)

# Display the ndarray
print("Array A:")
print(A)


# 1. Using a property of ndarray
# A.shape shows the size of the array (rows, columns)
print("\n1. Property: A.shape")
print("Shape of A:", A.shape)


# 2. Using a method of ndarray
# A.max() returns the highest value in the array
print("\n2. Method: A.max()")
print("Maximum value in A:", A.max())


# 3. Using a numpy function
# np.max(A) also returns the highest value
print("\n3. NumPy Function: np.max(A)")
print("Maximum value using NumPy:", np.max(A))

Array A:
[[ 10  20  25  30  40]
 [ 45  50  60  65  70]
 [ 75  80  90  95 100]]

1. Property: A.shape
Shape of A: (3, 5)

2. Method: A.max()
Maximum value in A: 100

3. NumPy Function: np.max(A)
Maximum value using NumPy: 100


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [16]:
%cd /content/drive/MyDrive/IS110_BPerformance_Maravilla/IS110_repo_Maravilla

/content/drive/MyDrive/IS110_BPerformance_Maravilla/IS110_repo_Maravilla


In [6]:
%cd /content/drive/MyDrive/IS110_BPerformance_Maravilla

/content/drive/MyDrive/IS110_BPerformance_Maravilla


In [7]:
pwd

'/content/drive/MyDrive/IS110_BPerformance_Maravilla'

In [8]:
!cp /content/drive/MyDrive/IS110_BPerformance_Maravilla/NumpyExercise.ipynb /content/drive/MyDrive/IS110_BPerformance_Maravilla/IS110_repo_Maravilla/PythonEnvi_Maravilla/chapters_maravilla

In [18]:
!git add PythonEnvi_Maravilla/chapters_maravilla/NumpyExercise.ipynb

In [19]:
!git commit -m "commit"

On branch main
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    chapter2_maravilla.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	PythonEnvi_Maravilla/env_maravilla/

no changes added to commit (use "git add" and/or "git commit -a")


In [22]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address


In [17]:
!git config --global user.email 'louienapaula.maravilla@students.isatu.edu.ph'
!git config --global user.name 'louienapaulamaravilla-sys'

In [21]:
!git remote set-url origin https://github.com/louienapaulamaravilla-sys/IS110_repo_Maravilla.git

In [ ]:
!git remote set-url origin https://YOUR_USERNAME:YOUR_TOKEN@github.com/louienapaulamaravilla-sys/IS110_repo_Maravilla.git